### ISSUE TITLE
In-Memory Databases are not really pooled/shared

### ISSUE THREAD

**Issue by gwenn** [ivanceras/r2d2-sqlite#1]
Hi,
https://www.sqlite.org/inmemorydb.html:

> The database ceases to exist as soon as the database connection is closed. Every :memory: database is distinct from every other. So, opening two database connections each with the filename ":memory:" will create two independent in-memory databases.

Regards.

**Comment by ivanceras** [comment]
Yes, we can't do anything about it for now.

**Comment by gwenn** [comment]
Are you sure ?
https://github.com/jgallagher/rusqlite/blob/master/src/lib.rs#L180
http://sqlite.org/c3ref/open.html
http://sqlite.org/uri.html
```rust
SqliteConnectionManager::new(PathBuf::from("file:dummy.db?mode=memory&cache=shared"),
             SQLITE_OPEN_URI | SQLITE_OPEN_CREATE | SQLITE_OPEN_READ_WRITE)
```
...

**Comment by SergioBenitez** [comment]
Just ran into this. It makes absolutely no sense to me to create a pool of connections if each connection refers to a different in-memory database.

**Comment by ivanceras** [comment]
I just make it a pool to have a uniform code for accessing the connection. If you have a better improvement, I'll take a PR.

**Comment by gwenn** [comment]
A PR removing the following entries:
 - https://github.com/ivanceras/r2d2-sqlite/blob/master/src/lib.rs#L102
 - https://github.com/ivanceras/r2d2-sqlite/blob/master/src/lib.rs#L109
will be accepted ?

**Comment by gwenn** [comment]
It seems to me that the issue has been fixed by https://github.com/ivanceras/r2d2-sqlite/commit/f0a7bdd605cc1e87cf846241385722a99682bfee .
