### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by jaemk** [ivanceras/r2d2-sqlite#13]
Is it safe to bump from 0.3 to 0.3.1 when rusqlite versions 0.12 and 0.13 are incompatible?  Couldn't there be a case where someone has the dependencies

```
rusqlite = "0.12"
r2d2_sqlite = "0.3"
```

And then doing a `cargo update` would cause an error from trying to link to different versions of libsqlite3-sys?

**Comment by ivanceras** [comment]
Oh, I just realized that it is 0.12 to 0.13 in rusqlite. I have to release 0.4 and yank out 0.3.1 then. 
Thanks @jaemk

**Comment by jaemk** [comment]
Thanks for fixing it!
