### ISSUE TITLE
0.5.1 introduced a breaking change, violating semver

### ISSUE THREAD

**Issue by SergioBenitez** [ivanceras/r2d2-sqlite#19]
The commit https://github.com/ivanceras/r2d2-sqlite/commit/57c0d65d25e3bc2e02cd416f1eeb83cf51dd28d6 is part of `0.5.1`, which updates `rusqlite` from `0.13` to `0.14`. Because `rusqlite` is part of the public API via [`SqliteConnectionManager::Connection`](https://docs.rs/r2d2_sqlite/0.5.1/r2d2_sqlite/struct.SqliteConnectionManager.html), this is a breaking change in `r2d2-sqlite`. Thus, you _must_ bump the version to `0.6.0`.

To properly fix this issue, please yank `0.5.1` and instead release `0.6.0`.

**Comment by ivanceras** [comment]
Thanks @SergioBenitez,

I knew I should have bumped it to 0.6.0, but choose to just bump a minor version thinking it was okay. I've just learn 1 more about semver.

I just yanked 0.5.1 and published 0.6.0 
https://github.com/ivanceras/r2d2-sqlite/commit/52555a725dc0aeac100c2237b0cb2b4ab685070d
