### ISSUE TITLE
Update to rusqlite 0.23

### ISSUE THREAD

**Issue by jsgf** [ivanceras/r2d2-sqlite#35]
rusqlite prior to 0.23 has various memory safety issues [RUSTSEC-2020-0014](https://rustsec.org/advisories/RUSTSEC-2020-0014.html): https://github.com/rusqlite/rusqlite/releases/tag/0.23.0

**Comment by ivanceras** [comment]
Fixed in https://github.com/ivanceras/r2d2-sqlite/pull/36
