### ISSUE TITLE
Adding num_thread in new 

### ISSUE THREAD

**Issue by Rustixir** [ivanceras/r2d2-sqlite#43]
Hi, When I wanted use CLI for specify number thread cannot found a simple way for add to that
and I add num_thread, to **Pool::new(Manager, num_thread)** if I choice a bad way please say me    

![Screenshot from 2021-10-19 01-11-47](https://user-images.githubusercontent.com/89704186/137810998-a8c61720-5b20-4a2e-b2f9-30f68933775f.png)

**Comment by 0x2b00b1e5** [comment]
The [`build()`](https://docs.rs/r2d2/0.8.9/r2d2/struct.Builder.html#method.build) method only takes a `manager`. If you want to specify the thread pool, use [`Builder::thread_pool()`](https://docs.rs/r2d2/0.8.9/r2d2/struct.Builder.html#method.thread_pool`).

**Comment by Rustixir** [comment]
My reason is, I do not know how many CPUs I can buy for my program. I just want to write now
After purchase, when start microservice,  read from the env file or some other way.
