### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Rustixir** [ivanceras/r2d2-sqlite#44]
I wrote a benchmark 
rusqlite (single-thread) vs r2d2-sqlite (default 4 thread)

**scenario :** 
create **in-memory** table and fills it  after done,  
spawn 100 concurrent ( tokio task ) and each one execute query (Select many row)
and i used r2d2-sqlite in a task and it concurrent execute over pool.get
but performance always is same.

(Each query is time consuming and I'm sure it has enough time to run concurrent)

actually r2d2-sqlite ( concurrent ) 
Not increase throughtout
Not decrease latency

why ??  

( my purpose is read-heavy)

**Comment by 0x2b00b1e5** [comment]
The query is time consuming since it needs to read lots of data from the hard disk, which in itself will always take much longer than getting a connection from the pool.

**Comment by Rustixir** [comment]
What is best practice usage of pool of sqlite ??

**Comment by Rustixir** [comment]
i wrote another benchmark,
like last benchmark just i changed query to very very simple 
in this rustqlite again was better in throughout and latency
