### ISSUE TITLE
Running commands just prior to closing DB connection

### ISSUE THREAD

**Issue by evolutics** [ivanceras/r2d2-sqlite#48]
Thanks for maintaining this library.

There is already a method `SqliteConnectionManager::with_init` to run commands just after _opening_ a DB connection.

Symmetrically, users may wish to run commands just before _closing_ a DB connection. For instance, the SQLite documentation shows how to use the [optimize pragma](https://www.sqlite.org/lang_analyze.html) prior to closing each connection for purposes of query optimization.

I think it'd be helpful if r2d2-sqlite could give an example of this, which is possible with `r2d2::CustomizeConnection::on_release` (see below). Alternatively, r2d2-sqlite could provide a dedicated method, basically the counterpart of `with_init` – although that'd make it's API less minimal.

Here is an example with a configuration I use:

```rust
use r2d2::CustomizeConnection;
use r2d2::Pool;
use r2d2_sqlite::SqliteConnectionManager;
use rusqlite::Connection;

const AFTER_CONNECT: &str = "PRAGMA foreign_keys=1;
PRAGMA journal_mode=WAL;
PRAGMA synchronous=NORMAL;";

const BEFORE_DISCONNECT: &str = "PRAGMA analysis_limit=400;
PRAGMA optimize;";

pub fn get_db_connection_pool() -> Pool<SqliteConnectionManager> {
    Pool::builder()
        .connection_customizer(Box::new(ConnectionCustomizer))
        .build(
            SqliteConnectionManager::file("file.db").with_init(|connection| {
                println!("Connecting.");
                connection.execute_batch(AFTER_CONNECT)
            }),
        )
        .unwrap()
}

#[derive(Debug)]
struct ConnectionCustomizer;

impl<E> CustomizeConnection<Connection, E> for ConnectionCustomizer {
    fn on_release(&self, connection: Connection) {
        println!("Disconnecting.");
        connection.execute_batch(BEFORE_DISCONNECT).unwrap()
    }
}
```

I can work the example into a pull request for the documentation but wanted to know your thoughts first.

**Comment by 0x2b00b1e5** [comment]
So I guess you're looking for a func called `with_close`? 

It shouldn't be too hard to implement. I'll try to look into it but I am quite busy lately.

**Comment by evolutics** [comment]
Supporting such a function `with_close` is one option.

However, in hindsight, I prefer reusing the `r2d2::CustomizeConnection` API for this purpose as in the example above. This keeps r2d2-sqlite's API more minimal, hence maintainable. But up to you of course.

Closing this as I have a solution. Feel free to reopen. I can help document above pattern, too.
