### ISSUE TITLE
Wrong syntax for bind parameters

### ISSUE THREAD

**Issue by gwenn** [ivanceras/r2d2-sqlite#8]
In the [header](https://github.com/ivanceras/r2d2-sqlite/blob/master/src/lib.rs#L27) documentation, the syntax should be:
```rust
//!             conn.execute("INSERT INTO foo (bar) VALUES (?1)", &[&i]).unwrap();
```
(the `$` is replaced by a `?`).
See [here](https://github.com/jgallagher/rusqlite/issues/177) for further explanations.

**Comment by ivanceras** [comment]
Fixed https://github.com/ivanceras/r2d2-sqlite/commit/865f0a081a9a974ba9af78b8c5cb93f530cf4db7
